name: expense
networks: 
  default: 
    name: expense
  # external: ture #use if you created network already in server
volumes:
  mysql:
services:
  mysql:
    image: mysql:v2
    build: mysql/.
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1  
    # ports:
    #   - "8000:5000"
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume 
  backend:
    image: backend:v2
    build: backend/.
    container_name: backend
    command: sh -c "sleep 40 && node /opt/server/index.js"
    depends_on:
      - db
  frontend:
    image: frontend:v2
    build: frontend/.
    container_name: frontend
    ports:
      - "80:80"
    