name: expense
networks: 
  expense:
  # external: ture #use if you created network already in server
volumes:
  expense_data:
services:
  db:
    image: db:v1
    build: db/.
    container_name: db
    networks:
      - expense
    # ports:
    #   - "8000:5000"
    volumes:
      - expense_data:/var/lib/mysql
  backend:
    image: backend:v1
    build: backend/.
    container_name: backend
    command: sh -c "sleep 20 && /opt/server/index.js"
    depends_on:
      - db
    networks:
      - expense
  frontend:
    image: frontend:v1
    build: frontend/.
    container_name: frontend
    networks:
      - expense
    ports:
      - "80:80"
    